#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 27, 2018 03:46:29 PM IST  platform: Windows NT

import sys
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def cleared(self):

        self.tusername.delete(0, 'end')
        self.tusername.insert(0,"")
        self.tpassword.delete(0, 'end')
        self.tpassword.insert(0,"")
       		
    def clicked(self):
        username=self.tusername.get()
        password=self.tpassword.get()
        import pymysql;
        conn= pymysql.connect(host='localhost',user='root',passwd='admin',db='school');
        cur=conn.cursor()
        cur.execute('select * from tbadmin where username="%s" and password="%s"' % \
		   		(username,password))
        rows = cur.fetchall()
        r=len(rows)	
        if (r==0):
            self.Label3.configure(text='''Login unsuccessful''')
        else:
            self.Label3.configure(text='''Login Successful''')		
			
    def passwd(self):
       print(os.system("forgotpwd.py"))
       self.destroy_Toplevel1();	
        	
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("600x450+447+130")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.2, rely=0.2, height=21, width=59)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Username''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.2, rely=0.289, height=31, width=64)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Password''')

        self.tusername = tk.Entry(top)
        self.tusername.place(relx=0.333, rely=0.2,height=20, relwidth=0.273)
        self.tusername.configure(background="white")
        self.tusername.configure(disabledforeground="#a3a3a3")
        self.tusername.configure(font="TkFixedFont")
        self.tusername.configure(foreground="#000000")
        self.tusername.configure(highlightbackground="#d9d9d9")
        self.tusername.configure(highlightcolor="black")
        self.tusername.configure(insertbackground="black")
        self.tusername.configure(selectbackground="#c4c4c4")
        self.tusername.configure(selectforeground="black")

        self.tpassword = tk.Entry(top)
        self.tpassword.place(relx=0.333, rely=0.311,height=20, relwidth=0.273)
        self.tpassword.configure(background="white")
        self.tpassword.configure(disabledforeground="#a3a3a3")
        self.tpassword.configure(font="TkFixedFont")
        self.tpassword.configure(foreground="#000000")
        self.tpassword.configure(highlightbackground="#d9d9d9")
        self.tpassword.configure(highlightcolor="black")
        self.tpassword.configure(insertbackground="black")
        self.tpassword.configure(selectbackground="#c4c4c4")
        self.tpassword.configure(selectforeground="black")

        self.bsave = tk.Button(top)
        self.bsave.place(relx=0.333, rely=0.422, height=24, width=157)
        self.bsave.configure(activebackground="#ececec")
        self.bsave.configure(activeforeground="#000000")
        self.bsave.configure(background="#d9d9d9")
        self.bsave.configure(disabledforeground="#a3a3a3")
        self.bsave.configure(foreground="#000000")
        self.bsave.configure(highlightbackground="#d9d9d9")
        self.bsave.configure(highlightcolor="black")
        self.bsave.configure(pady="0")
        self.bsave.configure(text='''login''')
        self.bsave.configure(command=self.clicked)
		
		
        self.bclear = tk.Button(top)
        self.bclear.place(relx=0.333, rely=0.533, height=24, width=157)
        self.bclear.configure(activebackground="#ececec")
        self.bclear.configure(activeforeground="#000000")
        self.bclear.configure(background="#d9d9d9")
        self.bclear.configure(disabledforeground="#a3a3a3")
        self.bclear.configure(foreground="#000000")
        self.bclear.configure(highlightbackground="#d9d9d9")
        self.bclear.configure(highlightcolor="black")
        self.bclear.configure(pady="0")
        self.bclear.configure(text='''Clear''')
        self.bclear.configure(command=self.cleared)

        self.bchange = tk.Button(top)
        self.bchange.place(relx=0.333, rely=0.644, height=24, width=157)
        self.bchange.configure(activebackground="#ececec")
        self.bchange.configure(activeforeground="#000000")
        self.bchange.configure(background="#d9d9d9")
        self.bchange.configure(disabledforeground="#a3a3a3")
        self.bchange.configure(foreground="#000000")
        self.bchange.configure(highlightbackground="#d9d9d9")
        self.bchange.configure(highlightcolor="black")
        self.bchange.configure(pady="0")
        self.bchange.configure(text='''Forgot Password''')
        self.bchange.configure(command=self.passwd)
		
        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.35, rely=0.755, height=21, width=200)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''''')

if __name__ == '__main__':
    vp_start_gui()





