#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 03, 2019 10:58:36 AM IST  platform: Windows NT

import sys
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import savepg_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    savepg_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    savepg_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def add(self):
        print(os.system("fees.py"))
        self.master.destroy()
    def edit(self):
        print(os.system("receipt.py"))	
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Sitka Small} -size 15 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"

        top.geometry("600x450+354+199")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.267, rely=0.178, height=61, width=334)
        self.Label1.configure(activebackground="#ef2bc1")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#000000")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(borderwidth="10")
        self.Label1.configure(compound="center")
        self.Label1.configure(disabledforeground="#ff30f8")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#59ef2b")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(highlightthickness="10")
        self.Label1.configure(relief='ridge')
        self.Label1.configure(state='active')
        self.Label1.configure(text='''FEES''')
        self.Label1.configure(underline="50")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.4, rely=0.467, height=24, width=127)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''add fees''')
        self.Button1.configure(width=127)
        self.Button1.configure(command=self.add)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.4, rely=0.622, height=24, width=127)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''edit fees''')
        self.Button2.configure(width=127)
        self.Button2.configure(command=self.edit)

if __name__ == '__main__':
    vp_start_gui()





