#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 02, 2019 02:16:12 PM IST  platform: Windows NT

import sys
import os

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import studentpg_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    studentpg_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    studentpg_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def add(self):
      print(os.system("newstudent.py"))
      self.destroy_Toplevel1()
    def edit(self):
      print(os.system("editadm.py"))
      self.destroy_Toplevel1()	  
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("600x486+320+179")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.233, rely=0.185, height=51, width=304)
        self.Label1.configure(background="#5bd4d8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''STUDENT''')
        self.Label1.configure(underline="2")
        self.Label1.configure(width=304)

        self.badd = tk.Button(top)
        self.badd.place(relx=0.25, rely=0.556, height=24, width=95)
        self.badd.configure(activebackground="#ececec")
        self.badd.configure(activeforeground="#000000")
        self.badd.configure(background="#d9d9d9")
        self.badd.configure(disabledforeground="#a3a3a3")
        self.badd.configure(foreground="#000000")
        self.badd.configure(highlightbackground="#d9d9d9")
        self.badd.configure(highlightcolor="black")
        self.badd.configure(pady="0")
        self.badd.configure(text='''ADD''')
        self.badd.configure(width=95)
        self.badd.configure(command=self.add)		

        self.bedit = tk.Button(top)
        self.bedit.place(relx=0.667, rely=0.556, height=24, width=95)
        self.bedit.configure(activebackground="#ececec")
        self.bedit.configure(activeforeground="#000000")
        self.bedit.configure(background="#d9d9d9")
        self.bedit.configure(disabledforeground="#a3a3a3")
        self.bedit.configure(foreground="#000000")
        self.bedit.configure(highlightbackground="#d9d9d9")
        self.bedit.configure(highlightcolor="black")
        self.bedit.configure(pady="0")
        self.bedit.configure(text='''EDIT''')
        self.bedit.configure(width=95)
        self.bedit.configure(command=self.edit)

if __name__ == '__main__':
    vp_start_gui()





