#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 27, 2018 03:55:09 AM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop66" "Popupmenu4" vTcl:WidgetProc "" 1
    .pop66 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {} -font TkMenuFont \
        -foreground {#000000} -label Insert 
    .pop66 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {} -font TkMenuFont \
        -foreground {#000000} -label Save 
    menu .pop77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop77" "Popupmenu5" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d8ae3a} -colormap {} 
    wm focusmodel $top passive
    wm geometry $top 600x450+436+140
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but44 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Sum 
    vTcl:DefineAlias "$top.but44" "Sum" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.ent45.che49 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Check -variable che49 
    vTcl:DefineAlias "$top.ent45.che49" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text hindi 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text english 
    vTcl:DefineAlias "$top.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent48" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent50" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text punjabi 
    vTcl:DefineAlias "$top.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text percentage 
    vTcl:DefineAlias "$top.but52" "percentage" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text maths 
    vTcl:DefineAlias "$top.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent54" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Check -variable che55 
    vTcl:DefineAlias "$top.che55" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra57 \
        -borderwidth 2 -relief groove -background {#d8254f} -height 65 \
        -width 455 
    vTcl:DefineAlias "$top.fra57" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    labelframe $site_3_0.lab59 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background {#d9d9d9} -height 75 -width 150 
    vTcl:DefineAlias "$site_3_0.lab59" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 270 -y 250 -anchor nw -bordermode ignore 
    labelframe $top.lab60 \
        -font TkDefaultFont -foreground black -text Address \
        -background {#d9d9d9} -height 75 -width 150 
    vTcl:DefineAlias "$top.lab60" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad67 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Radio -variable {} 
    vTcl:DefineAlias "$top.rad67" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    scale $top.sca68 \
        -activebackground {#ececec} -background {#d9d9d9} -bigincrement 0.0 \
        -font TkTextFont -foreground {#000000} -from 0.0 \
        -highlightbackground {#d9d9d9} -highlightcolor black -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca68" "Scale1" vTcl:WidgetProc "Toplevel1" 1
    scale $top.sca69 \
        -activebackground {#ececec} -background {#d9d9d9} -bigincrement 0.0 \
        -font TkTextFont -foreground {#000000} -from 0.0 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -orient horizontal -resolution 1.0 -tickinterval 0.0 -to 100.0 \
        -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca69" "Scale2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che70 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Check -variable che70 
    vTcl:DefineAlias "$top.che70" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes71 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Message \
        -width 60 
    vTcl:DefineAlias "$top.mes71" "Message1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $top.tCh72 \
        -variable tch72 -takefocus {} -text Tcheck 
    vTcl:DefineAlias "$top.tCh72" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    spinbox $top.spi73 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$top.spi73" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    scale $top.sca74 \
        -activebackground {#ececec} -background {#d9d9d9} -bigincrement 0.0 \
        -font TkTextFont -foreground {#000000} -from 0.0 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -orient horizontal -resolution 1.0 -tickinterval 0.0 -to 100.0 \
        -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca74" "Scale3" vTcl:WidgetProc "Toplevel1" 1
    spinbox $top.spi75 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$top.spi75" "Spinbox2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo76 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo76" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad78 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Radio -variable {} 
    vTcl:DefineAlias "$top.rad78" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn79 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn79" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    spinbox $top.spi80 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$top.spi80" "Spinbox3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent81 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent81" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex82 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 10 -wrap word 
    .top42.tex82 configure -font TkTextFont
    .top42.tex82 insert end text
    vTcl:DefineAlias "$top.tex82" "Text1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TRadiobutton -background #d9d9d9
    ttk::style configure TRadiobutton -foreground #000000
    ttk::style configure TRadiobutton -font TkDefaultFont
    ttk::radiobutton $top.tRa83 \
        -variable {} -takefocus {} -text TRadio 
    vTcl:DefineAlias "$top.tRa83" "TRadiobutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font TkDefaultFont
    ttk::panedwindow $top.tPa84 \
        -orient horizontal 
    vTcl:DefineAlias "$top.tPa84" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa84.p1 \
        -text {Pane 1} -width 105 -height 200 
    vTcl:DefineAlias "$top.tPa84.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa84.p1
    $top.tPa84 add $top.tPa84.p1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa84.p2 \
        -text {Pane 2} -width 95 -height 200 
    vTcl:DefineAlias "$top.tPa84.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa84.p2
    $top.tPa84 add $top.tPa84.p2 
        
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but44 \
        -in $top -x 90 -y 250 -width 145 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 200 -y 100 -anchor nw -bordermode ignore 
    place $top.ent45.che49 \
        -in $top.ent45 -x 100 -y 80 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 90 -y 100 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 90 -y 130 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 200 -y 130 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 200 -y 160 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 90 -y 160 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 90 -y 280 -width 140 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 90 -y 190 -width 39 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 200 -y 190 -anchor nw -bordermode ignore 
    place $top.che55 \
        -in $top -x 430 -y 120 -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 80 -y 370 -width 455 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 360 -y 270 -anchor nw -bordermode ignore 
    place $top.rad67 \
        -in $top -x 370 -y 30 -anchor nw -bordermode ignore 
    place $top.sca68 \
        -in $top -x 530 -y 170 -anchor nw -bordermode ignore 
    place $top.sca69 \
        -in $top -x 430 -y 80 -anchor nw -bordermode ignore 
    place $top.che70 \
        -in $top -x 250 -y 20 -anchor nw -bordermode ignore 
    place $top.mes71 \
        -in $top -x 430 -y 180 -anchor nw -bordermode ignore 
    place $top.tCh72 \
        -in $top -x 90 -y 330 -anchor nw -bordermode ignore 
    place $top.spi73 \
        -in $top -x 190 -y 340 -anchor nw -bordermode ignore 
    place $top.sca74 \
        -in $top -x 400 -y 220 -anchor nw -bordermode ignore 
    place $top.spi75 \
        -in $top -x 250 -y 230 -anchor nw -bordermode ignore 
    place $top.tCo76 \
        -in $top -x 450 -y 30 -anchor nw -bordermode ignore 
    place $top.rad78 \
        -in $top -x 290 -y 290 -anchor nw -bordermode ignore 
    place $top.tEn79 \
        -in $top -x 30 -y 10 -anchor nw -bordermode ignore 
    place $top.spi80 \
        -in $top -x 10 -y 80 -anchor nw -bordermode ignore 
    place $top.ent81 \
        -in $top -x 20 -y 220 -anchor nw -bordermode ignore 
    place $top.tex82 \
        -in $top -x 10 -y 280 -anchor nw -bordermode ignore 
    place $top.tRa83 \
        -in $top -x 330 -y 70 -anchor nw -bordermode ignore 
    place $top.tPa84 \
        -in $top -x 140 -y 40 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

